server:
  port: 8082

spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessActivity
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/