server:
  port: 8083

spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
