spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/fitness-oauth2/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/users/**

        - id: dashboard
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/dashboard/**

        - id: activityservice
          uri: lb://ACTIVITYSERVICE
          predicates:
            - Path=/api/activities/**

        - id: aiservice
          uri: lb://AISERVICE
          predicates:
            - Path=/api/recommendations/**

server:
  port: 8080
