spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: riyagrover
    password: ""   # or remove this line if password is not set
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081