spring:
  application:
    name: UserService

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: riyagrover
    password:  # <--- leave this blank but include the key

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
